import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { CssBaseline } from "@mui/material"
import ContainerProvider from "@/components/organisms/Provider"
import "@assets/styles/globals.scss"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <CssBaseline />
        <ContainerProvider>{children}</ContainerProvider>
      </body>
    </html>
  )
}
